import DatabaseModel from './DatabaseModel'
// import config from '../../config'

export default function CbbGamesPlayers(postgres) {
  const factoryToExtend = DatabaseModel(postgres, 'cbb_games_players')

  return Object.assign(
    factoryToExtend,
    {
      accessibleColumns: [
        'game_id',
        'season',
        'neutral_site',
        'scheduled_date',
        'gametime',
        'tournament',
        'tournament_type',
        'tournament_round',
        'tournament_game_no',
        'player_id',
        'last_name',
        'first_name',
        'full_name',
        'abbr_name',
        'status',
        'jersey_number',
        'height',
        'weight',
        'birth_place',
        'birthplace_city',
        'birthplace_state',
        'birthplace_country',
        'class',
        'team_name',
        'team_market',
        'team_id',
        'team_alias',
        'conf_name',
        'conf_alias',
        'division_name',
        'division_alias',
        'league_name',
        'home_team',
        'active',
        'played',
        'starter',
        'minutes',
        'minutes_int64',
        'position',
        'primary_position',
        'field_goals_made',
        'field_goals_att',
        'field_goals_pct',
        'three_points_made',
        'three_points_att',
        'three_points_pct',
        'two_points_made',
        'two_points_att',
        'two_points_pct',
        'blocked_att',
        'free_throws_made',
        'free_throws_att',
        'free_throws_pct',
        'offensive_rebounds',
        'defensive_rebounds',
        'rebounds',
        'assists',
        'turnovers',
        'steals',
        'blocks',
        'assists_turnover_ratio',
        'personal_fouls',
        'tech_fouls',
        'flagrant_fouls',
        'points'
      ]
    }
  )
}
